// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: danmaku.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Clean-room schema derived from BiliKit's own M4 contract observations.
/// Keep generator and runtime pinned to SwiftProtobuf 1.38.1 (ADR 0008).

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Bilikit_Danmaku_SegmentReply: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var elements: [Bilikit_Danmaku_Element] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Bilikit_Danmaku_Element: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: Int64 = 0

  var progressMilliseconds: Int32 = 0

  var mode: Int32 = 0

  var fontSize: Int32 = 0

  var colorRgb: UInt32 = 0

  var senderHash: String = String()

  var content: String = String()

  var createdAt: Int64 = 0

  var weight: Int32 = 0

  var action: String = String()

  var pool: Int32 = 0

  var idString: String = String()

  var attributes: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "bilikit.danmaku"

nonisolated extension Bilikit_Danmaku_SegmentReply: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SegmentReply"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}elements\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.elements) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.elements.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.elements, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Bilikit_Danmaku_SegmentReply, rhs: Bilikit_Danmaku_SegmentReply) -> Bool {
    if lhs.elements != rhs.elements {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Bilikit_Danmaku_Element: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Element"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}progress_milliseconds\0\u{1}mode\0\u{3}font_size\0\u{3}color_rgb\0\u{3}sender_hash\0\u{1}content\0\u{3}created_at\0\u{1}weight\0\u{1}action\0\u{1}pool\0\u{3}id_string\0\u{1}attributes\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.progressMilliseconds) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.mode) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.fontSize) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.colorRgb) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.senderHash) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.content) }()
      case 8: try { try decoder.decodeSingularInt64Field(value: &self.createdAt) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self.weight) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.action) }()
      case 11: try { try decoder.decodeSingularInt32Field(value: &self.pool) }()
      case 12: try { try decoder.decodeSingularStringField(value: &self.idString) }()
      case 13: try { try decoder.decodeSingularInt32Field(value: &self.attributes) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularInt64Field(value: self.id, fieldNumber: 1)
    }
    if self.progressMilliseconds != 0 {
      try visitor.visitSingularInt32Field(value: self.progressMilliseconds, fieldNumber: 2)
    }
    if self.mode != 0 {
      try visitor.visitSingularInt32Field(value: self.mode, fieldNumber: 3)
    }
    if self.fontSize != 0 {
      try visitor.visitSingularInt32Field(value: self.fontSize, fieldNumber: 4)
    }
    if self.colorRgb != 0 {
      try visitor.visitSingularUInt32Field(value: self.colorRgb, fieldNumber: 5)
    }
    if !self.senderHash.isEmpty {
      try visitor.visitSingularStringField(value: self.senderHash, fieldNumber: 6)
    }
    if !self.content.isEmpty {
      try visitor.visitSingularStringField(value: self.content, fieldNumber: 7)
    }
    if self.createdAt != 0 {
      try visitor.visitSingularInt64Field(value: self.createdAt, fieldNumber: 8)
    }
    if self.weight != 0 {
      try visitor.visitSingularInt32Field(value: self.weight, fieldNumber: 9)
    }
    if !self.action.isEmpty {
      try visitor.visitSingularStringField(value: self.action, fieldNumber: 10)
    }
    if self.pool != 0 {
      try visitor.visitSingularInt32Field(value: self.pool, fieldNumber: 11)
    }
    if !self.idString.isEmpty {
      try visitor.visitSingularStringField(value: self.idString, fieldNumber: 12)
    }
    if self.attributes != 0 {
      try visitor.visitSingularInt32Field(value: self.attributes, fieldNumber: 13)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Bilikit_Danmaku_Element, rhs: Bilikit_Danmaku_Element) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.progressMilliseconds != rhs.progressMilliseconds {return false}
    if lhs.mode != rhs.mode {return false}
    if lhs.fontSize != rhs.fontSize {return false}
    if lhs.colorRgb != rhs.colorRgb {return false}
    if lhs.senderHash != rhs.senderHash {return false}
    if lhs.content != rhs.content {return false}
    if lhs.createdAt != rhs.createdAt {return false}
    if lhs.weight != rhs.weight {return false}
    if lhs.action != rhs.action {return false}
    if lhs.pool != rhs.pool {return false}
    if lhs.idString != rhs.idString {return false}
    if lhs.attributes != rhs.attributes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
